stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/data.csv
    outs:
      - data/preprocessed.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/preprocessed.csv
    # Remove 'outs' for model.pkl
